import time
import os
import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
import datetime
from rag_engine import get_answer
from src.config import TICKERS, HISTORY_PATH

# --- CONFIGURATION ---
st.set_page_config(
    page_title="Real-Time Market AI", 
    page_icon="📈", 
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("⚡ Real-Time Financial Market Analyst")

# --- UTILITY FUNCTIONS ---
def fmt_relative(ts: float) -> str:
    """Formats timestamp into 'X min ago'."""
    if not ts: 
        return "n/a"
    try:
        delta = max(int(time.time() - float(ts)), 0)
        if delta < 60: 
            return f"{delta}s ago"
        if delta < 3600: 
            return f"{delta // 60}m ago"
        if delta < 86400: 
            return f"{delta // 3600}h ago"
        return f"{delta // 86400}d ago"
    except:
        return "n/a"

def fmt(val):
    """Format numeric values with 2 decimal places."""
    if val is None or val == 'N/A' or val != val:
        return "N/A"
    try:
        return f"{float(val):.2f}"
    except:
        return str(val)

def check_system_health() -> tuple[str, str]:
    """Checks if the Consumer is actively writing to the heartbeat file."""
    heartbeat_file = os.path. join(HISTORY_PATH, "consumer_heartbeat.txt")
    status = "🔴 OFFLINE"
    color = "red"
    
    if os.path.exists(heartbeat_file):
        try:
            with open(heartbeat_file, "r") as f:
                last_beat = float(f.read().strip())
            
            delta = time.time() - last_beat
            if delta < 120:
                status = "🟢 ONLINE"
                color = "green"
            else:
                status = f"🟠 LAGGING ({int(delta)}s)"
                color = "orange"
        except:
            pass
    
    return status, color

def display_stock_chart(ticker: str) -> None:
    """Reads the local CSV history (generated by Kafka) and plots it with both MA50 and MA200."""
    csv_file = os.path.join(HISTORY_PATH, f"{ticker}.csv")

    if not os.path.exists(csv_file):
        st.info(f"⏳ Waiting for Kafka stream to populate data for {ticker}...")
        return

    try:
        # ✅ Lire le CSV
        data = pd.read_csv(csv_file)
        
        # ✅ La première colonne est l'index (date)
        if data.columns[0] != "date":
            data = data. rename(columns={data.columns[0]: "date"})
        
        data = data.set_index("date")
        data.index = pd.to_datetime(data.index, errors='coerce')
        
        # ✅ Normaliser et convertir les colonnes en numériques
        data.columns = [col.strip().capitalize() for col in data.columns]
        
        # Convertir en float (remplace les erreurs par NaN)
        for col in ["Open", "High", "Low", "Close", "Volume"]:
            if col in data.columns:
                data[col] = pd.to_numeric(data[col], errors='coerce')
        
        # Supprimer les lignes avec NaN
        data = data.dropna(subset=["Open", "High", "Low", "Close"])
        
        if data.empty: 
            st. warning("📊 CSV vide ou données invalides")
            return

        # Candle Chart
        fig = go.Figure(data=[go.Candlestick(
            x=data.index,
            open=data["Open"],
            high=data["High"],
            low=data["Low"],
            close=data["Close"],
            name=ticker
        )])

        # Moving Average 50j
        if len(data) > 50:
            ma50 = data["Close"].rolling(window=50).mean()
            fig.add_trace(go.Scatter(
                x=data.index, 
                y=ma50, 
                mode="lines", 
                name="MA 50", 
                line=dict(color="orange", width=2)
            ))

        # Moving Average 200j
        if len(data) > 200:
            ma200 = data["Close"].rolling(window=200).mean()
            fig.add_trace(go.Scatter(
                x=data.index, 
                y=ma200, 
                mode="lines", 
                name="MA 200", 
                line=dict(color="blue", width=2)
            ))

        fig.update_layout(
            title=f"{ticker} (Source: Kafka/Local)", 
            height=450, 
            template="plotly_dark"
        )
        st.plotly_chart(fig, use_container_width=True)

    except Exception as e:  
        st. error(f"Chart Error: {e}")
        
# --- SIDEBAR: PIPELINE STATUS & MARKET WATCH ---
@st.cache_data(ttl=60)
def get_sidebar_data() -> list[dict]:
    """Fetches live price snapshots for sidebar (Cached)."""
    results = []
    for ticker in TICKERS:
        try:
            stock = yf.Ticker(ticker)
            info = stock.fast_info
            market_state = stock.info.get("marketState", "CLOSED")
            results.append({
                "ticker": ticker,
                "price": info.last_price,
                "prev": info.previous_close,
                "currency": info.currency,
                "market_state": market_state
            })
        except:
            pass
    return results

def display_sidebar() -> None:
    """Displays the sidebar with system status and market watch."""
    # --- PIPELINE STATUS ---
    status, color = check_system_health()
    st.sidebar.markdown(f"### Pipeline Status: :{color}[{status}]")
    
    if st.sidebar.button("🔄 Refresh Data"):
        st.rerun()
    
    st.sidebar. divider()
    
    # --- MARKET WATCH ---
    st.sidebar.subheader("📈 Market Watch")
    market_data = get_sidebar_data()
    
    for item in market_data:
        delta = ((item['price'] - item['prev']) / item['prev']) * 100
        color_delta = "green" if delta >= 0 else "red"
        icon = "▲" if delta >= 0 else "▼"
        
        # Market State Indicator
        market_indicator = "🟢" if item['market_state'] == "REGULAR" else "🔴"
        
        # ✅ LINE 1: Ticker + Market State
        st.sidebar.markdown(f"**{item['ticker']}** {market_indicator}")
        
        # ✅ LINE 2: Price + Currency + Evolution %
        st.sidebar.markdown(
            f"{item['price']:.4f} {item['currency']} :{color_delta}[{icon} {delta:.2f}%]"
        )
        
        # ✅ LINE 3: Date and Time of last price
        try:
            stock = yf.Ticker(item['ticker'])
            last_price_time = stock.info.get('regularMarketTime')
            if last_price_time:
                if isinstance(last_price_time, int):
                    from datetime import datetime
                    dt = datetime.fromtimestamp(last_price_time)
                    time_str = dt. strftime("%A %d/%m/%Y %H:%M")
                else:
                    time_str = str(last_price_time)
            else:
                time_str = "N/A"
        except: 
            time_str = "N/A"
        
        st.sidebar.caption(f"📅 {time_str}")
        st.sidebar.divider()
display_sidebar()

# --- MAIN LAYOUT ---
col1, col2 = st.columns([2, 1])

with col1:
    # --- AI ANALYST SECTION ---
    with st.container():
        st.markdown("### 🤖 AI Market Analyst")
        with st.form(key="query_form"):
            query = st.text_input(
                "Ask about market trends, news, or technicals:",
                placeholder="Why is Stellantis dropping right now?"
            )
            submit = st.form_submit_button("Analyze", type="primary")

    if submit and query:
        with st.spinner("🧠 Agent is analyzing Kafka streams..."):
            answer, sources, ticker, horizon = get_answer(query)
            
            # Display Analysis Mode
            horizon_hours = round(horizon / 3600, 1)
            mode_label = "🔴 LIVE MODE" if horizon_hours < 4 else "📚 HISTORY MODE"
            st.caption(f"{mode_label} | Search Window: Last {horizon_hours} hours")
            
            # Display Answer
            st.success("✅ Analysis Complete")
            st.markdown(answer)
            
            # Display Chart if ticker detected
            if ticker:
                st.divider()
                display_stock_chart(ticker)

# --- SOURCES PANEL ---
with col2:
    st.subheader("📡 Context Sources")
    
    if 'sources' in locals() and sources:
        for s in sources:
            # --- TECHNICAL ANALYSIS SOURCE ---
            if s['type'] == 'technical':  
                icon = "📈"
                relative_time = fmt_relative(s. get('timestamp'))
                
                # ✅ RÉCUPÉRER L'ÉTAT RÉEL DU MARCHÉ
                try:
                    stock = yf.Ticker(s['ticker'])
                    market_state = stock.info.get("marketState", "CLOSED")
                    if market_state == "REGULAR":
                        market_display = "🟢 OPEN"
                        market_color = "green"
                    else:
                        market_display = "🔴 CLOSED"
                        market_color = "red"
                except:
                    market_display = "❓ UNKNOWN"
                    market_color = "gray"
                
                with st.expander(f"{icon} {s['ticker']} - Technical Analysis ({relative_time})"):
                    # En-tête compact
                    st.caption(f"📅 {s['date']} | :{market_color}[{market_display}]")
                    
                    # ✅ CURRENT PRICES - Sans titre séparé
                    price_parts = []
                    if s.get('current_price'):
                        price_parts.append(f"Current Price : {fmt(s['current_price'])} {s.get('currency', '')}")
                    if s.get('last_close'):
                        price_parts.append(f"Close: {fmt(s['last_close'])}")
                    if s.get('opening_price'):
                        price_parts.append(f"Open: {fmt(s['opening_price'])}")
                    if price_parts:
                        st.write(" | ".join(price_parts))
                    
                    # ✅ TECHNICAL LEVELS - Sur une ligne
                    ma_parts = []
                    if s.get('mean_10'):
                        ma_parts.append(f"MA10: {fmt(s['mean_10'])}")
                    if s.get('mean_50'):
                        ma_parts.append(f"MA50: {fmt(s['mean_50'])}")
                    if s.get('mean_200'):
                        ma_parts.append(f"MA200: {fmt(s['mean_200'])}")
                    if ma_parts:
                        st.write(" | ".join(ma_parts))
                    
                    # ✅ PRICE HISTORY - Sur une ligne
                    price_history = []
                    if s.get('price_12h_ago'): 
                        price_history.append(f"12h: {fmt(s['price_12h_ago'])}")
                    if s.get('price_6h_ago'): 
                        price_history.append(f"6h: {fmt(s['price_6h_ago'])}")
                    if s.get('price_3h_ago'): 
                        price_history.append(f"3h: {fmt(s['price_3h_ago'])}")
                    if s.get('price_1h_ago'): 
                        price_history.append(f"1h: {fmt(s['price_1h_ago'])}")
                    if s.get('price_30min_ago'): 
                        price_history.append(f"30m: {fmt(s['price_30min_ago'])}")
                    if s.get('price_10min_ago'): 
                        price_history.append(f"10m: {fmt(s['price_10min_ago'])}")
                    if price_history:
                        st.write(" | ".join(price_history))
                    
                    # ✅ LIEN - Minimal
                    if s.get('link') and s['link'] != "#":
                        st.markdown(f"[📖 Read more]({s['link']})")

            # --- NEWS SOURCE ---
            elif s['type'] == 'news':
                icon = "📰"
                relative_time = fmt_relative(s.get('timestamp'))
                
                with st.expander(f"{icon} {s['ticker']} - News ({relative_time})"):
                    st.caption(f"📅 {s['date']}")
                    st.write(f"{s['title']}")
                    
                    # Sentiment Score with visual indicator
                    sentiment_score = s.get('sentiment')
                    if sentiment_score is not None and sentiment_score != "N/A":
                        try:
                            sentiment_float = float(sentiment_score)
                            # Color code sentiment
                            if sentiment_float > 0.5:
                                sentiment_label = "🟢 Positive"
                                sentiment_color = "green"
                            elif sentiment_float < -0.5:
                                sentiment_label = "🔴 Negative"
                                sentiment_color = "red"
                            else: 
                                sentiment_label = "⚪ Neutral"
                                sentiment_color = "gray"
                            
                            st.write(f"**Sentiment:** :{sentiment_color}[{sentiment_label} ({sentiment_float:.2f})]")
                        except:
                            pass
                    
                    st.divider()
                    if s.get('link') and s['link'] != "#":
                        st.markdown(f"[📖 Read full article]({s['link']})")
            
            # --- INTRADAY METRICS SOURCE ---
            elif s['type'] == 'intraday_metrics':
                icon = "📊"
                relative_time = fmt_relative(s.get('timestamp'))
                try:
                    stock = yf.Ticker(s['ticker'])
                    market_state = stock.info.get("marketState", "CLOSED")
                    if market_state == "REGULAR":
                        market_display = "🟢 OPEN"
                        market_color = "green"
                    else:
                        market_display = "🔴 CLOSED"
                        market_color = "red"
                except:
                    market_display = "❓ UNKNOWN"
                    market_color = "gray"
                
                with st.expander(f"{icon} {s['ticker']} - Intraday Metrics ({relative_time})"):
                    st.caption(f"📅 {s['date']} - Market: {market_display}")
                    
                    # ✅ Utiliser 'title' au lieu de 'doc'
                    if s.get('title'):
                        content = s['title']
                        
                        # Nettoyer les **
                        content = content.replace('**', '')
                        
                        # Remplacer les carrés colorés par des triangles
                        content = content.replace('🟩', '▲')
                        content = content.replace('🟥', '▼')
                        
                        st.write(content)
                    
                    # Link minimal
                    if s.get('link') and s['link'] != "#":
                        st.markdown(f"[📖 View details]({s['link']})")
                
            else:
                st.info("📌 Sources will appear here after analysis.")

# --- FOOTER ---
st. markdown("---")
st.caption("🏗️ Architecture: Kafka Stream → Consumer → ChromaDB → Llama 3 (Groq) | Real-Time Market Data")