import time
import os
import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
import datetime
from rag_engine import get_answer
from src.config import TICKERS, HISTORY_PATH

# --- CONFIGURATION ---
st.set_page_config(
    page_title="Real-Time Market AI", 
    page_icon="📈", 
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("⚡ Real-Time Financial RAG")

def fmt_relative(ts: float) -> str:
    """Formats timestamp into 'X min ago'."""
    if not ts: return "n/a"
    try:
        delta = max(int(time.time() - float(ts)), 0)
        if delta < 60: return f"{delta}s ago"
        if delta < 3600: return f"{delta // 60}m ago"
        if delta < 86400: return f"{delta // 3600}h ago"
        return f"{delta // 86400}d ago"
    except:
        return "n/a"
    

def check_system_health() -> tuple[str, str]:
    """Checks if the Consumer is actively writing to the heartbeat file."""
    heartbeat_file = os.path.join(HISTORY_PATH, "consumer_heartbeat.txt")
    status = "🔴 OFFLINE"
    color = "red"
    
    if os.path.exists(heartbeat_file):
        try:
            with open(heartbeat_file, "r") as f:
                last_beat = float(f.read().strip())
            
            delta = time.time() - last_beat
            if delta < 120: # Less than 2 minutes lag
                status = "🟢 ONLINE"
                color = "green"
            else:
                status = f"🟠 LAGGING ({int(delta)}s)"
                color = "orange"
        except:
            pass
            
    return status, color


def display_stock_chart(ticker: str) -> None:
    """Reads the local CSV history (generated by Kafka) and plots it."""
    csv_file = os.path.join(HISTORY_PATH, f"{ticker}.csv")

    if not os.path.exists(csv_file):
        st.info(f"⏳ Waiting for Kafka stream to populate data for {ticker}...")
        return

    try:
        data = pd.read_csv(csv_file, index_col="date", parse_dates=True)
        if data.empty: return

        # Candle Chart
        fig = go.Figure(data=[go.Candlestick(
            x=data.index,
            open=data["Open"],
            high=data["High"],
            low=data["Low"],
            close=data["Close"],
            name=ticker
        )])

        # Moving Average
        if len(data) > 50:
            data["MA50"] = data["Close"].rolling(window=50).mean()
            fig.add_trace(go.Scatter(x=data.index, y=data["MA50"], mode="lines", name="MA 50", line=dict(color="orange", width=1)))

        fig.update_layout(
            title=f"Live Chart: {ticker}", 
            height=400, 
            margin=dict(l=20, r=20, t=40, b=20),
            template="plotly_dark",
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='rgba(0,0,0,0)'
        )
        st.plotly_chart(fig, use_container_width=True)

    except Exception as e:
        st.error(f"Chart Error: {e}")


@st.cache_data(ttl=60) # Cache for 60s to prevent UI lag
def get_sidebar_data() -> list[dict]:
    """Fetches live price snapshots for sidebar (Cached)."""
    results = []
    for ticker in TICKERS:
        try:
            stock = yf.Ticker(ticker)
            info = stock.fast_info
            results.append({
                "ticker": ticker,
                "price": info.last_price,
                "prev": info.previous_close,
                "currency": info.currency
            })
        except:
            pass
    return results

def display_sidebar() -> None:
    """Displays the sidebar with system status and market watch."""
    status, color = check_system_health()
    st.sidebar.markdown(f"### Pipeline Status: :{color}[{status}]")
    
    if st.sidebar.button("🔄 Refresh Data"):
        st.rerun()
        
    st.sidebar.divider()
    st.sidebar.subheader("Market Watch")
    
    market_data = get_sidebar_data()
    
    for item in market_data:
        delta = ((item['price'] - item['prev']) / item['prev']) * 100
        color_delta = "green" if delta >= 0 else "red"
        icon = "▲" if delta >= 0 else "▼"
        
        st.sidebar.markdown(
            f"**{item['ticker']}**\n"
            f"{item['price']:.2f} {item['currency']} "
            f":{color_delta}[{icon} {delta:.2f}%]"
        )
        st.sidebar.divider()

display_sidebar()

# --- MAIN LAYOUT ---
col1, col2 = st.columns([2, 1])

with col1:
    # Query Section
    with st.container():
        st.markdown("### 🤖 AI Market Analyst")
        with st.form(key="query_form"):
            query = st.text_input("Ask about market trends, news, or technicals:", placeholder="Why is Stellantis dropping right now?")
            submit = st.form_submit_button("Analyze", type="primary")

    if submit and query:
        with st.spinner("🧠 Agent is analyzing Kafka streams..."):
            # Call the RAG Engine
            answer, sources, ticker, horizon = get_answer(query)
            
            # Display Horizon Badge
            horizon_hours = round(horizon / 3600, 1)
            mode_label = "🔴 LIVE MODE" if horizon_hours < 4 else "📚 HISTORY MODE"
            st.caption(f"{mode_label} | Search Window: Last {horizon_hours} hours")
            
            # Display Answer
            st.markdown(answer)
            
            # Display Chart if ticker detected
            if ticker:
                st.divider()
                display_stock_chart(ticker)

with col2:
    st.subheader("Context Sources")
    
    if 'sources' in locals() and sources:
        for s in sources:
            # Determine Icon based on type
            if s['type'] == 'intraday_metrics': icon = "📊"
            elif s['type'] == 'technical': icon = "📈"
            else: icon = "📰"
            
            relative_time = fmt_relative(s.get('timestamp'))
            
            with st.expander(f"{icon} {s['ticker']} ({relative_time})"):
                st.caption(f"Time: {s['date']}")
                st.markdown(f"**{s['title']}**")
                
                # Show Price Metrics inside source expander
                if s.get('current_price'):
                    st.markdown(f"Price: **{s['current_price']:.2f}**")
                    if s.get('mean_200'):
                        st.caption(f"MA200: {s['mean_200']:.2f}")
                
                if s.get('link') and s['link'] != "#":
                    st.markdown(f"[Open Source]({s['link']})")
    else:
        st.info("Sources will appear here after analysis.")

# Footer
st.markdown("---")
st.caption("Architecture: Kafka Stream -> Consumer -> ChromaDB -> Llama 3 (Groq)")